development:
  adapter: postgresql
  encoding: unicode
  database: jelp_development
  pool: 5
  username: rsj
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: jelp_test
  pool: 5
  username: rsj
  password: 
